services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
